version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Library.API/Dockerfile
    depends_on:
        - mssql
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: mssql